/*
 * This source file was generated by the Gradle 'init' task
 */
package sigarka;

// File: src/main/java/com/payroll/MainApp.java

import javafx.application.Application;
import javafx.stage.Stage;
import sigarka.scenes.LoginSc;

public class MainApp extends Application {

    @Override
    public void start(Stage stage) {

        stage.setTitle("SIGARKA");
        stage.setScene(LoginSc.createScene(stage));
        stage.show();
    }

    public static void main(String[] args) {
        launch();
    }
}